# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160414_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 13, 29, 9, 327977, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=datetime.datetime(2016, 4, 14, 13, 29, 23, 279285, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 13, 29, 29, 47967, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 13, 29, 34, 260314, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
